#include <stdio.h>

#include "config.h"
#include "debug.h"
#include "stack.h"
#include "vm.h"

// Generated by make
#include "version.h"

int main(int argc, char** argv) {
    printf("git short hash: %s\n", GIT_SHORT_HASH);
    printf("git long hash: %s\n", GIT_LONG_HASH);
    printf("build date: %s\n", DATE);

    struct vm_s *vm = init_vm();
    enum opcode_e program[] = {
        OPCODE_TRUE,
        OPCODE_TRUE,
        OPCODE_POP,
        OPCODE_POP
    };

    const int program_length = sizeof(program) / sizeof(*program);
    DEBUG("INFO", "program length: %d", program_length);
    for(int i = 0; i < program_length; i++) {
        enum opcode_e opcode = program[i];
        DEBUG("INFO", "opcode: 0x%x", opcode);
        void (*handler) () = *(vm->opcode_dispatch_table + opcode);
        handler(vm);
        printf("stack: {");
        for(int i = 0; i < vm->stack->current_position; i++) {
            printf("%d", vm->stack->stack[i]);
            if(i < vm->stack->current_position - 1) {
                printf(", ");
            }
        }
        printf("}\n");
    }
    destroy_vm(vm);
    return 0;
}
